version: 0.2

phases:
  install:
    commands:
      - "apt install wget unzip -y"
      - "wget https://releases.hashicorp.com/terraform/1.1.9/terraform_1.1.9_linux_amd64.zip"
      - "unzip terraform_1.1.9_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"
  pre_build:
    commands:
      - terraform init

  build:
    commands:
      - terraform $TF_COMMAND -auto-approve

  post_build:
    commands:
      - echo Terraform $TF_COMMAND completed on `date`